site_name: Loupe Factory Docs
site_description: Documentation for Loupe Factory platform and its features.
site_url: https://docs.loupefactory.com
site_author: Aditya Jain
copyright: Copyright &copy; 2025 Loupe AI, LLC

# Theme configuration
theme:
  name: material
  language: en
  
  # Color palette matching Phoenix theme
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  # Typography matching Phoenix theme
  font:
    text: Nunito Sans
    code: JetBrains Mono

  # Features for professional documentation
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Icon configuration
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      repository: adityajain2408/loupe-factory-external-docs
      branch: main
  - git-committers:
      repository: adityajain2408/loupe-factory-external-docs
      branch: main

# Customization
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quick-start.md
  - API Reference:
    - Core API: api/core.md
    - Authentication: api/auth.md
    - Endpoints: api/endpoints.md
  - Contributing:
    - Development: contributing/development.md
    - Guidelines: contributing/guidelines.md
    - Testing: contributing/testing.md

# Additional configuration
extra:
  version:
    provider: mike
    default: latest

  social:
    - icon: simple/linkedin
      link: https://linkedin.com/company/LoupeAI

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.